// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV-hI4aag6POiFEAkqT2-_w81RPcYkrJk',
    appId: '1:849037601373:web:793371601f3d25717afbb4',
    messagingSenderId: '849037601373',
    projectId: 'mykey-40dff',
    authDomain: 'mykey-40dff.firebaseapp.com',
    storageBucket: 'mykey-40dff.firebasestorage.app',
    measurementId: 'G-BPPNVHM46V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1mm2zWqDJ7e-IHN5BjrKvYg5C9PYrwU',
    appId: '1:849037601373:android:9eb92cefb337b5a57afbb4',
    messagingSenderId: '849037601373',
    projectId: 'mykey-40dff',
    storageBucket: 'mykey-40dff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAozBIJXShGAmXsB7qI4KSsPK24Wz-pynU',
    appId: '1:849037601373:ios:b13f327078edb9da7afbb4',
    messagingSenderId: '849037601373',
    projectId: 'mykey-40dff',
    storageBucket: 'mykey-40dff.firebasestorage.app',
    iosBundleId: 'com.example.mykey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAozBIJXShGAmXsB7qI4KSsPK24Wz-pynU',
    appId: '1:849037601373:ios:b13f327078edb9da7afbb4',
    messagingSenderId: '849037601373',
    projectId: 'mykey-40dff',
    storageBucket: 'mykey-40dff.firebasestorage.app',
    iosBundleId: 'com.example.mykey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV-hI4aag6POiFEAkqT2-_w81RPcYkrJk',
    appId: '1:849037601373:web:0676ef2a76e6bf1d7afbb4',
    messagingSenderId: '849037601373',
    projectId: 'mykey-40dff',
    authDomain: 'mykey-40dff.firebaseapp.com',
    storageBucket: 'mykey-40dff.firebasestorage.app',
    measurementId: 'G-7NTQ63SQY7',
  );
}
